// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApM7IRTC8rxOp-z-ey2CLwZOKDgPaiz5U',
    appId: '1:828458109496:web:881b6b5d44756c5d1d74cd',
    messagingSenderId: '828458109496',
    projectId: 'neat-8c41c',
    authDomain: 'neat-8c41c.firebaseapp.com',
    storageBucket: 'neat-8c41c.appspot.com',
    measurementId: 'G-Y0JHTT2ND7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4-S_erpBVEbK_zqznP5slfcYHDDkJZY',
    appId: '1:828458109496:android:1b1a2bef6477332c1d74cd',
    messagingSenderId: '828458109496',
    projectId: 'neat-8c41c',
    storageBucket: 'neat-8c41c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMO93p95RSmWgO_eOi3bpntuMznmjoxY',
    appId: '1:828458109496:ios:60dfc343585f18fe1d74cd',
    messagingSenderId: '828458109496',
    projectId: 'neat-8c41c',
    storageBucket: 'neat-8c41c.appspot.com',
    iosBundleId: 'com.example.neat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMO93p95RSmWgO_eOi3bpntuMznmjoxY',
    appId: '1:828458109496:ios:edceba54d3344a131d74cd',
    messagingSenderId: '828458109496',
    projectId: 'neat-8c41c',
    storageBucket: 'neat-8c41c.appspot.com',
    iosBundleId: 'com.example.neat.RunnerTests',
  );
}
